#!/bin/sh
echo "🧪 Running Tests and Coverage..."

./gradlew test jacocoTestReport --daemon
status=$?

if [ $status -ne 0 ]; then
    echo "❌ Tests failed. Fix them before pushing."
    exit 1
fi
exit 0