/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import java.util.Locale;

import org.example.app.view.controllers.PrimaryController;
import org.example.framework.i18n.LocalizationModule;
import org.example.fxloader.IContainer;
import org.example.fxloader.IFxLoader;
import org.example.style.CustomStyle;

import com.google.inject.Guice;
import com.google.inject.Injector;

import javafx.application.Application;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import org.jspecify.annotations.NonNull;

import static java.util.Objects.requireNonNull;

public final class App extends Application {

    private static final String[] LANG_BUNDLES = new String[]{"i18n.message.MessageBundle", "i18n.menu.MenuBundle"};

    @Override
    public void start(Stage primaryStage) throws Exception {
        Application.setUserAgentStylesheet(CustomStyle.getDefaultStylesheet());

        Injector injector = Guice.createInjector(new LocalizationModule(Locale.getDefault(), LANG_BUNDLES),
                new Module());
        IFxLoader loader = requireNonNull(injector.getInstance(IFxLoader.class));

        IContainer<@NonNull PrimaryController> loaded = loader.load(PrimaryController.class);
        Parent root = loaded.view();

        primaryStage.setTitle("Template");
        primaryStage.setMaximized(true);

        Scene scene = new Scene(root);
        primaryStage.setScene(scene);

        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
