/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.map.view;

import java.io.File;
import java.io.FileNotFoundException;

import com.gluonhq.attach.storage.StorageService;
import com.gluonhq.attach.util.Services;
import com.gluonhq.maps.MapView;

public class MapViewer extends MapView {

    public MapViewer() throws Exception {
        File privateStorage = Services.get(StorageService.class).flatMap(StorageService::getPrivateStorage)
                .orElseThrow(() -> new FileNotFoundException("Could Not Access Private Storage"));
        IO.println("Storage: " + privateStorage.getAbsolutePath());
    }

}
