CREATE ROLE app_user WITH LOGIN PASSWORD 'secret123' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
-- GRANT CONNECT ON DATABASE testdb TO app_user;
GRANT USAGE ON SCHEMA public TO app_user;
GRANT SELECT,
    INSERT,
    UPDATE,
    DELETE ON ALL TABLES IN SCHEMA public TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT,
    INSERT,
    UPDATE,
    DELETE ON TABLES TO app_user;