/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.map.view;

import org.junit.jupiter.api.Test;

class MapTestCase {
    @Test
    void testGetMessage() {
    }
}
